/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jotadev.gestao.vendas.visual.componentes;

/**
 *
 * @author Joanir
 */
public class Cartao extends javax.swing.JPanel {

    /**
     * Creates new form Cartao
     */
    public Cartao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCartaoIcon = new javax.swing.JLabel();
        labelCartaoTitulo = new javax.swing.JLabel();
        labelCartaoValor = new javax.swing.JLabel();

        labelCartaoTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelCartaoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCartaoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelCartaoTitulo.setText("Titulo");

        labelCartaoValor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCartaoValor.setForeground(new java.awt.Color(255, 255, 255));
        labelCartaoValor.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCartaoValor)
                    .addComponent(labelCartaoTitulo)
                    .addComponent(labelCartaoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCartaoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCartaoTitulo)
                .addGap(18, 18, 18)
                .addComponent(labelCartaoValor)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelCartaoIcon;
    private javax.swing.JLabel labelCartaoTitulo;
    private javax.swing.JLabel labelCartaoValor;
    // End of variables declaration//GEN-END:variables
}
